services:
  api:
    build: ./backend
    command: gunicorn stock_insight.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3
